// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Footer: typeof import('./components/Footer.vue')['default']
    ICarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    ICarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    'IFxemoji:blossom': typeof import('~icons/fxemoji/blossom')['default']
    'ILogos:tailwindcssIcon': typeof import('~icons/logos/tailwindcss-icon')['default']
    'ILogos:vitejs': typeof import('~icons/logos/vitejs')['default']
    'IRi:homeLine': typeof import('~icons/ri/home-line')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
